#!/usr/bin/env python3
"""Prose gate: banned characters and ASCII-substituted German in every file
this repository authors.

Two classes, both of which survive review because nobody sees them:

* the em dash (U+2014). The house style writes a hyphen or a comma. It
  arrives by copy-paste and by autocorrect, and once it sits in a comment
  block it is copied into the next repository with that block.
* characters that render as nothing: zero-width space, byte-order mark,
  soft hyphen, and the directional marks. They are legal text, they pass
  every structural check, and they break search and diffs silently.

Deliberately NOT flagged: the ellipsis, the en dash and the no-break space.
They are legitimate typography here, and a gate that fights legitimate
typography gets switched off.

``schema/`` is excluded because it is not authored here: it is a
byte-identical mirror of the pinned learn-content-engine release, held in
place by the drift gate. Its typography is the engine's to fix, and editing
it here would turn the drift gate red for a cosmetic reason.

The second class is the umlaut written as a letter pair: "fuer" for "für",
"Abhaengigkeit" for "Abhängigkeit", "heisst" for "heißt". It is legal text, it
passes every structural check, and a whole lesson set can be authored that way
without a single gate noticing - which is what happened once. The check never
matches the letter pair itself (a rule on "ue" fires on "value", "true" and
"queue"). It uses scripts/umlaut_stems.json, built from dictionaries by
scripts/build_umlaut_stems.py: short words as whole words, longer ones through
stems that occur in no correct German word, no English word and none of the
foreign-language material these repositories teach. It covers 98 percent of
the German dictionary's umlaut words; tests/test_check_prose.py re-proves
coverage and both false-alarm rates whenever the dictionaries are installed
(the Umlaut data workflow installs them).

Code is exempt from the umlaut check, and only from that one. An identifier is
spelled by whoever wrote it: "laeuft" as a variable name is a choice, "laeuft"
in a sentence is a misspelling. In a lesson file that means the code-bearing
fields (``passage``, ``sentence``, ``tokens``, ``code``) and the fenced blocks
inside a theory body; in Markdown it means the fenced blocks.

This file, its test, the stem generator and its data are exempt from the
umlaut check too, for the same reason the banned characters are built from
code points: a list of misspellings has to contain them. ``tests/test_check_prose.py`` asserts the
exemption, so it cannot quietly widen.

Usage:
    python3 scripts/check_prose.py             # gate every tracked file
    python3 scripts/check_prose.py --self-test # prove the gate bites
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
import unicodedata
from pathlib import Path

# Built from code points, never from literals: this file has to pass its own
# gate, and a table of the real characters would flag the gate itself.
BANNED = {
    chr(0x2014): "EM DASH (write a hyphen or a comma)",
    chr(0x200B): "ZERO WIDTH SPACE",
    chr(0xFEFF): "BYTE ORDER MARK",
    chr(0x00AD): "SOFT HYPHEN",
    chr(0x200E): "LEFT-TO-RIGHT MARK",
    chr(0x200F): "RIGHT-TO-LEFT MARK",
}

ALLOWED_SAMPLE = "a clean line - hyphen, comma, no-break space" + chr(0x00A0) + ", ellipsis" + chr(0x2026)

EXCLUDED_PREFIXES = ("schema/",)

# Generated by a bot from the manifests and never hand-edited: a finding here
# is a copy of a finding in a manifest, and the manifest is where it is fixed.
EXCLUDED_FILES = {"search-index.json"}

# The umlaut check's data, built from dictionaries (see the module docstring).
UMLAUT_DATA = json.loads(Path(__file__).with_name("umlaut_stems.json").read_text(encoding="utf-8"))
WHOLE_WORDS: dict[str, str] = UMLAUT_DATA["words"]
STEMS: dict[str, str] = UMLAUT_DATA["stems"]
UMLAUT_OF = {"ae": "\u00e4", "oe": "\u00f6", "ue": "\u00fc", "ss": "\u00df"}


def _pair_decisions(stem: str, correction: str) -> dict[int, str]:
    """Offset of every letter pair in ``stem`` -> what the correct word makes
    of it: the umlaut, or the pair itself ("ss" in "Zuverlässigkeit")."""
    decisions: dict[int, str] = {}
    i = j = 0
    while i < len(stem):
        pair = stem[i:i + 2]
        if pair in UMLAUT_OF:
            collapsed = correction[j] == UMLAUT_OF[pair]
            decisions[i] = UMLAUT_OF[pair] if collapsed else pair
            i, j = i + 2, j + (1 if collapsed else 2)
        else:
            i, j = i + 1, j + 1
    return decisions


STEM_DECISIONS = {stem: _pair_decisions(stem, correction) for stem, correction in STEMS.items()}
STEM_SIZES = sorted({len(stem) for stem in STEMS}, reverse=True)

# What the dictionaries cannot know. Measured on 2026-09-23 over the ten
# content repositories: a surname (Ulric Neisser, alc-psychology) and two
# Korean romanisations that sit in German prose of a Korean course. A new
# collision belongs here together with the run that found it.
FOREIGN_LOOKALIKES = {
    "neisser",
    "jinaesseo",
    "seonsaengnim",
}

# Fields of a lesson file that hold machine keys, not words: an id is looked up
# verbatim by the app and the manifest, so "correcting" its spelling silently
# renames the thing it names - and it is how a slug stops being ASCII without
# anyone noticing. Paths, URLs and enum-ish values are not sentences either.
# The stem generator skips these fields too when it reads foreign words.
MACHINE_KEYS = {
    "stable_id",
    "id",
    "theory_ref",
    "card_ids",
    "review_lesson_id",
    "variation_of",
    "tags",
    "example_url",
    "audio",
    "image",
    "src",
    "language",
    "media_type",
}

# Fields of a lesson file that carry CODE rather than prose: the code the
# learner reads, and the machine keys.
CODE_KEYS = {
    "passage",
    "sentence",
    "tokens",
    "code",
    "code_snippet",
    "code_language",
    "expected_output",
} | MACHINE_KEYS


# This gate and its test hold the misspellings on purpose.
UMLAUT_EXEMPT = (
    "scripts/check_prose.py",
    "tests/test_check_prose.py",
    "scripts/build_umlaut_stems.py",
    "scripts/umlaut_stems.json",
)

# A run of word characters joined by internal separators: a slug
# ("fuehrerschein-uebung"), a path ("sets/de/..."), a file name, a snake_case
# identifier, a URL. All lower case, it is a machine string, not a sentence -
# the repositories keep those ASCII on purpose. A capitalised hyphen compound
# ("Rueckgabe-Wert") is German prose and stays checked. The separator has to
# sit BETWEEN word characters, so a sentence-final "fuer." is still a word.
TECHNICAL_TOKEN = re.compile(r"[\w\u00c4\u00d6\u00dc\u00e4\u00f6\u00fc\u00df]+(?:[-_/.:][\w\u00c4\u00d6\u00dc\u00e4\u00f6\u00fc\u00df]+)+")

# Inline code: `x` and ``x``. Prose around it is checked, the span is not.
INLINE_CODE = re.compile(r"``[^`]*``|`[^`\n]*`")

WORD = re.compile("[A-Za-z\u00c4\u00d6\u00dc\u00e4\u00f6\u00fc\u00df]+")


def tracked_files() -> list[str]:
    """Every file git tracks, minus the mirrored artifacts."""
    # -z: without it git quotes a non-ASCII path ("f\\303\\274..."), the
    # quoted string is not a real path, and the file is skipped in silence -
    # a gate reporting clean over a file it never read.
    listing = subprocess.run(
        ["git", "ls-files", "-z"], capture_output=True, text=True, check=True
    ).stdout.split("\0")
    return [
        path
        for path in listing
        if path
        and not path.startswith(EXCLUDED_PREFIXES)
        and path not in EXCLUDED_FILES
    ]


def findings_in(text: str) -> list[tuple[int, str, str]]:
    """(line number, character, reason) for every banned character in ``text``."""
    findings = []
    for line_number, line in enumerate(text.splitlines(), start=1):
        for character, reason in BANNED.items():
            if character in line:
                findings.append((line_number, character, reason))
    return findings


def _stem_corrected(lowered: str) -> str:
    """``lowered`` with every letter pair a stem decides on replaced. Stems are
    looked up in the original word and the longest one decides a pair, so the
    result does not depend on the order stems are found in ("zurueckhaelt"
    carries two, "groessen" two pairs in one stem)."""
    if not any(pair in lowered for pair in UMLAUT_OF):
        return lowered
    matches = sorted(
        ((size, start) for start in range(len(lowered)) for size in STEM_SIZES
         if start + size <= len(lowered) and lowered[start:start + size] in STEMS),
        reverse=True,
    )
    decisions: dict[int, str] = {}
    for size, start in matches:
        for offset, outcome in STEM_DECISIONS[lowered[start:start + size]].items():
            decisions.setdefault(start + offset, outcome)
    pieces, index = [], 0
    while index < len(lowered):
        if index in decisions:
            pieces.append(decisions[index])
            index += 2
        else:
            pieces.append(lowered[index])
            index += 1
    return "".join(pieces)


def substituted_words(text: str) -> list[tuple[str, str]]:
    """(word, correct spelling) for every German word written without its
    umlauts in ``text``."""
    findings = []
    text = INLINE_CODE.sub(" ", text)
    text = TECHNICAL_TOKEN.sub(
        lambda match: " " if match.group(0) == match.group(0).lower() else match.group(0).replace("_", " "),
        text,
    )
    for word in WORD.findall(text):
        lowered = word.lower()
        if lowered in FOREIGN_LOOKALIKES or _is_identifier(word):
            continue
        if lowered in WHOLE_WORDS:
            suggestion = WHOLE_WORDS[lowered]
        else:
            suggestion = _stem_corrected(lowered)
        if word.isupper():
            # In capitals the sharp s is regularly written SS
            # ("AUSSCHLIESSLICH"), so only the umlaut half of a correction
            # applies to a shouted word.
            suggestion = suggestion.replace("\u00df", "ss")
        if suggestion == lowered:
            continue
        if word.isupper():
            suggestion = suggestion.upper()
        elif word[:1].isupper():
            suggestion = suggestion[:1].upper() + suggestion[1:]
        findings.append((word, suggestion))
    return findings


def _is_identifier(word: str) -> bool:
    """True for a camelCase word, which is code even inside a prose field.

    A prompt may name a function it is asking about
    ("fuegeOptimistischHinzu(text)"), and renaming it in prose would make the
    text point at something that does not exist. German never capitalises
    inside a word, so an inner capital next to lower case is a reliable
    marker. An all-caps word is not one: shouted German is still German.
    """
    has_inner_capital = any(character.isupper() for character in word[1:])
    return has_inner_capital and any(character.islower() for character in word)


def prose_segments(path: str, text: str) -> list[tuple[int, str]]:
    """(line number, prose) for the parts of a file the umlaut check applies to.

    A lesson file is walked as JSON so the code-bearing fields drop out; a
    Markdown file keeps everything outside its fenced blocks; anything else is
    prose end to end. Line numbers are best effort for JSON: the line the
    string starts on, looked up once per string.
    """
    if path.endswith(".json"):
        try:
            document = json.loads(text)
        except ValueError:
            return list(enumerate(text.splitlines(), start=1))
        collected: list[str] = []
        _walk_json(document, False, collected)
        lines = text.splitlines()
        segments = []
        for value in collected:
            head = value.splitlines()[0] if value.splitlines() else value
            line_no = next((i for i, line in enumerate(lines, start=1) if head[:60] in line), 0)
            segments.append((line_no, _outside_fences(value)))
        return segments
    if path.endswith(".md"):
        segments = []
        in_fence = False
        for number, line in enumerate(text.splitlines(), start=1):
            if line.lstrip().startswith("```"):
                in_fence = not in_fence
                continue
            if not in_fence:
                segments.append((number, line))
        return segments
    return list(enumerate(text.splitlines(), start=1))


def _walk_json(node, in_code: bool, out: list[str]) -> None:
    if isinstance(node, dict):
        # An inline example is prose when it is a sample sentence and code when
        # it declares a language; the field name alone cannot tell them apart.
        example_is_code = bool(node.get("language")) and "content" in node
        for key, value in node.items():
            child_is_code = in_code or key in CODE_KEYS or (example_is_code and key == "content")
            _walk_json(value, child_is_code, out)
    elif isinstance(node, list):
        for value in node:
            _walk_json(value, in_code, out)
    elif isinstance(node, str) and not in_code:
        out.append(node)


def _outside_fences(text: str) -> str:
    """The text with every fenced code block removed."""
    return " ".join(text.split("```")[0::2])


def describe(character: str) -> str:
    return f"U+{ord(character):04X} {unicodedata.name(character, 'UNNAMED')}"


def self_test() -> int:
    """A gate that never fires on a known-bad input is not a gate."""
    for character in BANNED:
        if not findings_in(f"a line with {character} in it"):
            print(f"self-test FAILED: {describe(character)} not detected", file=sys.stderr)
            return 1
    if findings_in(ALLOWED_SAMPLE):
        print("self-test FAILED: a clean line was flagged", file=sys.stderr)
        return 1

    if not substituted_words("Die Abhaengigkeitsliste laeuft"):
        print("self-test FAILED: substituted German not detected", file=sys.stderr)
        return 1
    for clean in ("value true Sequence queue useState", "Die Abh\u00e4ngigkeit l\u00e4uft \u00fcber Zuverl\u00e4ssigkeit"):
        if substituted_words(clean):
            print(f"self-test FAILED: flagged clean text {clean!r}", file=sys.stderr)
            return 1
    if substituted_words(_outside_fences("prose\n```js\nconst laeuft = true;\n```\nprose")):
        print("self-test FAILED: a fenced code block was scanned", file=sys.stderr)
        return 1

    print(
        f"self-test passed: {len(BANNED)} banned characters, "
        f"{len(WHOLE_WORDS)} whole words and {len(STEMS)} stems loaded, clean text untouched"
    )
    return 0


def main(argv: list[str]) -> int:
    if "--self-test" in argv:
        return self_test()

    files = tracked_files()
    if not files:
        print("check_prose: git tracks no files - wrong directory?", file=sys.stderr)
        return 2

    banned_hits = 0
    umlaut_hits = 0
    for path in files:
        try:
            text = Path(path).read_text(encoding="utf-8")
        except (UnicodeDecodeError, FileNotFoundError, IsADirectoryError):
            continue
        for line_number, character, reason in findings_in(text):
            banned_hits += 1
            print(f"{path}:{line_number}: {describe(character)} - {reason}")
        if path in UMLAUT_EXEMPT:
            continue
        for line_number, segment in prose_segments(path, text):
            for word, suggestion in substituted_words(segment):
                umlaut_hits += 1
                print(
                    f"{path}:{line_number}: {word} - German written without its"
                    f" umlaut, correct is {suggestion}"
                )

    if banned_hits or umlaut_hits:
        print(
            f"\nPROSE GATE: {banned_hits} banned character(s) and {umlaut_hits}"
            f" substituted German word(s) in {len(files)} tracked file(s).",
            file=sys.stderr,
        )
        return 1
    print(f"prose gate: {len(files)} tracked file(s) clean")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
